package com.lcxsfront.mapper;

import java.util.List;

import com.lcxsfront.model.caseBean;

public interface caseBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_case
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_case
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    int insert(caseBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_case
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    int insertSelective(caseBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_case
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    caseBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_case
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    int updateByPrimaryKeySelective(caseBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_case
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    int updateByPrimaryKey(caseBean record);
    /**
     * 根据产品pid查询对应方案
     */
    List<caseBean> queryCaseByPid(Long pid);
}