package com.lcxsfront.mapper;

import java.util.List;

import com.lcxsfront.model.noteBean;

public interface noteBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Mon Mar 26 14:30:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Mon Mar 26 14:30:59 CST 2018
     */
    int insert(noteBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Mon Mar 26 14:30:59 CST 2018
     */
    int insertSelective(noteBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Mon Mar 26 14:30:59 CST 2018
     */
    noteBean selectByPrimaryKey(noteBean note);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Mon Mar 26 14:30:59 CST 2018
     */
    int updateByPrimaryKeySelective(noteBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Mon Mar 26 14:30:59 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(noteBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Mon Mar 26 14:30:59 CST 2018
     */
    int updateByPrimaryKey(noteBean record);
    /**
     * 查询所有公告
     */
    List<noteBean> queryNote(noteBean note);
    /**
     * 分页查询所有公告
     */
    List<noteBean> queryNoteOnFY(noteBean note);
}