package com.lcxsfront.mapper;

import java.util.List;

import com.lcxsfront.model.productBean;

public interface productBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    int insert(productBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    int insertSelective(productBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    productBean selectByPid(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    int updateByPrimaryKeySelective(productBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(productBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    int updateByPrimaryKey(productBean record);
    /**
     * 查询所有产品信息
     */
    List<productBean> queryAllProduct(productBean product);
}