package com.lcxsfront.mapper;

import java.util.List;

import com.lcxsfront.model.frontBean;
import com.lcxsfront.model.receiptBean;

public interface receiptBeanMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_receipt
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_receipt
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	int insert(receiptBean record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_receipt
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	int insertSelective(receiptBean record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_receipt
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	receiptBean selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_receipt
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	int updateByPrimaryKeySelective(receiptBean record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_receipt
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	int updateByPrimaryKey(receiptBean record);
	/**
     * 查询总返利额
     */
    Object queryTotalMoney();
    /**
     * 查询总投资金额
     */
    Object queryTmoney();
    /**
     * 查询总用户
     */
    List<Object> qeuryUser();
    /**
     * 根据产品id查询有多少人投了这个产品
     */
    Object queryNumByProductId(Long id);
    /**
     * 根据vid查询用户回单
     */
    List<frontBean> queryReceiptByVidForApp(frontBean front);
}