package com.lcxsfront.mapper;

import java.util.List;

import com.lcxsfront.model.redBean;

public interface redBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_red
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_red
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    int insert(redBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_red
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    int insertSelective(redBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_red
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    redBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_red
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    int updateByPrimaryKeySelective(redBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_red
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    int updateByPrimaryKey(redBean record);
    /*
     * 查询所有能领取的红包
     */
    List<redBean> queryAllRed();
}