package com.lcxsfront.mapper;

import com.lcxsfront.model.userBeankBean;

public interface userBeankBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Mon Mar 26 11:57:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Mon Mar 26 11:57:03 CST 2018
     */
    int insert(userBeankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Mon Mar 26 11:57:03 CST 2018
     */
    int insertSelective(userBeankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Mon Mar 26 11:57:03 CST 2018
     */
    userBeankBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Mon Mar 26 11:57:03 CST 2018
     */
    int updateByPrimaryKeySelective(userBeankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Mon Mar 26 11:57:03 CST 2018
     */
    int updateByPrimaryKey(userBeankBean record);
}