package com.lcxsfront.mapper;

import com.lcxsfront.model.userReceiptBean;

public interface userReceiptBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    int insert(userReceiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    int insertSelective(userReceiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    userReceiptBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    int updateByPrimaryKeySelective(userReceiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    int updateByPrimaryKey(userReceiptBean record);
}