package com.lcxsfront.model;

public class caseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.id
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private Long id;
    private String qx;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.productid
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private Long productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.cid
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.casename
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String casename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.project
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.money
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.interest
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private Double interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.rebate
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private Double rebate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.red
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String red;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.experience
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private Double experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.other
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.tincome
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String tincome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.ybh
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String ybh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.zincome
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String zincome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.ftime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String ftime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.tprice
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String tprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.top
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private Integer top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.status
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.dtime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String dtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.texttime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String texttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_case.ctime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    private String ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.id
     *
     * @return the value of c_case.id
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.id
     *
     * @param id the value for c_case.id
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.productid
     *
     * @return the value of c_case.productid
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.productid
     *
     * @param productid the value for c_case.productid
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.cid
     *
     * @return the value of c_case.cid
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.cid
     *
     * @param cid the value for c_case.cid
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.casename
     *
     * @return the value of c_case.casename
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getCasename() {
        return casename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.casename
     *
     * @param casename the value for c_case.casename
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setCasename(String casename) {
        this.casename = casename == null ? null : casename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.project
     *
     * @return the value of c_case.project
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.project
     *
     * @param project the value for c_case.project
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.money
     *
     * @return the value of c_case.money
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.money
     *
     * @param money the value for c_case.money
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.interest
     *
     * @return the value of c_case.interest
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public Double getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.interest
     *
     * @param interest the value for c_case.interest
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setInterest(Double interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.rebate
     *
     * @return the value of c_case.rebate
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public Double getRebate() {
        return rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.rebate
     *
     * @param rebate the value for c_case.rebate
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setRebate(Double rebate) {
        this.rebate = rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.red
     *
     * @return the value of c_case.red
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getRed() {
        return red;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.red
     *
     * @param red the value for c_case.red
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setRed(String red) {
        this.red = red == null ? null : red.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.experience
     *
     * @return the value of c_case.experience
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public Double getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.experience
     *
     * @param experience the value for c_case.experience
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setExperience(Double experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.other
     *
     * @return the value of c_case.other
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.other
     *
     * @param other the value for c_case.other
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.tincome
     *
     * @return the value of c_case.tincome
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getTincome() {
        return tincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.tincome
     *
     * @param tincome the value for c_case.tincome
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setTincome(String tincome) {
        this.tincome = tincome == null ? null : tincome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.ybh
     *
     * @return the value of c_case.ybh
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getYbh() {
        return ybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.ybh
     *
     * @param ybh the value for c_case.ybh
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setYbh(String ybh) {
        this.ybh = ybh == null ? null : ybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.zincome
     *
     * @return the value of c_case.zincome
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getZincome() {
        return zincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.zincome
     *
     * @param zincome the value for c_case.zincome
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setZincome(String zincome) {
        this.zincome = zincome == null ? null : zincome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.ftime
     *
     * @return the value of c_case.ftime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getFtime() {
        return ftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.ftime
     *
     * @param ftime the value for c_case.ftime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setFtime(String ftime) {
        this.ftime = ftime == null ? null : ftime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.tprice
     *
     * @return the value of c_case.tprice
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getTprice() {
        return tprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.tprice
     *
     * @param tprice the value for c_case.tprice
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setTprice(String tprice) {
        this.tprice = tprice == null ? null : tprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.top
     *
     * @return the value of c_case.top
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.top
     *
     * @param top the value for c_case.top
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.status
     *
     * @return the value of c_case.status
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.status
     *
     * @param status the value for c_case.status
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.dtime
     *
     * @return the value of c_case.dtime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.dtime
     *
     * @param dtime the value for c_case.dtime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setDtime(String dtime) {
        this.dtime = dtime == null ? null : dtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.texttime
     *
     * @return the value of c_case.texttime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getTexttime() {
        return texttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.texttime
     *
     * @param texttime the value for c_case.texttime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setTexttime(String texttime) {
        this.texttime = texttime == null ? null : texttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_case.ctime
     *
     * @return the value of c_case.ctime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_case.ctime
     *
     * @param ctime the value for c_case.ctime
     *
     * @mbggenerated Tue Mar 27 16:08:38 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

	public String getQx() {
		return qx;
	}

	public void setQx(String qx) {
		this.qx = qx;
	}
}