package com.lcxsfront.model;

public class receiptBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.id
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.rid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private Long rid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.shopname
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private String shopname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.productid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private Long productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.productname
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private String productname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.caseid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private Long caseid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.tmoney
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private Double tmoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.jmoney
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private Double jmoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.channel
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private String channel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.realname
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.phone
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.status
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.auditor
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private String auditor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.context
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private String context;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.ttime
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private String ttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.ctime
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private String ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.mtime
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private String mtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.redmoney
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private Double redmoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_receipt.redid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	private Long redid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.id
	 * @return  the value of c_receipt.id
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.id
	 * @param id  the value for c_receipt.id
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.rid
	 * @return  the value of c_receipt.rid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public Long getRid() {
		return rid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.rid
	 * @param rid  the value for c_receipt.rid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setRid(Long rid) {
		this.rid = rid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.shopname
	 * @return  the value of c_receipt.shopname
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public String getShopname() {
		return shopname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.shopname
	 * @param shopname  the value for c_receipt.shopname
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setShopname(String shopname) {
		this.shopname = shopname == null ? null : shopname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.productid
	 * @return  the value of c_receipt.productid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public Long getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.productid
	 * @param productid  the value for c_receipt.productid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setProductid(Long productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.productname
	 * @return  the value of c_receipt.productname
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public String getProductname() {
		return productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.productname
	 * @param productname  the value for c_receipt.productname
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setProductname(String productname) {
		this.productname = productname == null ? null : productname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.caseid
	 * @return  the value of c_receipt.caseid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public Long getCaseid() {
		return caseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.caseid
	 * @param caseid  the value for c_receipt.caseid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setCaseid(Long caseid) {
		this.caseid = caseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.tmoney
	 * @return  the value of c_receipt.tmoney
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public Double getTmoney() {
		return tmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.tmoney
	 * @param tmoney  the value for c_receipt.tmoney
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setTmoney(Double tmoney) {
		this.tmoney = tmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.jmoney
	 * @return  the value of c_receipt.jmoney
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public Double getJmoney() {
		return jmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.jmoney
	 * @param jmoney  the value for c_receipt.jmoney
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setJmoney(Double jmoney) {
		this.jmoney = jmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.channel
	 * @return  the value of c_receipt.channel
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.channel
	 * @param channel  the value for c_receipt.channel
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setChannel(String channel) {
		this.channel = channel == null ? null : channel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.realname
	 * @return  the value of c_receipt.realname
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.realname
	 * @param realname  the value for c_receipt.realname
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setRealname(String realname) {
		this.realname = realname == null ? null : realname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.phone
	 * @return  the value of c_receipt.phone
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.phone
	 * @param phone  the value for c_receipt.phone
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.status
	 * @return  the value of c_receipt.status
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.status
	 * @param status  the value for c_receipt.status
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.auditor
	 * @return  the value of c_receipt.auditor
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public String getAuditor() {
		return auditor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.auditor
	 * @param auditor  the value for c_receipt.auditor
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setAuditor(String auditor) {
		this.auditor = auditor == null ? null : auditor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.context
	 * @return  the value of c_receipt.context
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public String getContext() {
		return context;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.context
	 * @param context  the value for c_receipt.context
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setContext(String context) {
		this.context = context == null ? null : context.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.ttime
	 * @return  the value of c_receipt.ttime
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public String getTtime() {
		return ttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.ttime
	 * @param ttime  the value for c_receipt.ttime
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setTtime(String ttime) {
		this.ttime = ttime == null ? null : ttime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.ctime
	 * @return  the value of c_receipt.ctime
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public String getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.ctime
	 * @param ctime  the value for c_receipt.ctime
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setCtime(String ctime) {
		this.ctime = ctime == null ? null : ctime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.mtime
	 * @return  the value of c_receipt.mtime
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public String getMtime() {
		return mtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.mtime
	 * @param mtime  the value for c_receipt.mtime
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setMtime(String mtime) {
		this.mtime = mtime == null ? null : mtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.redmoney
	 * @return  the value of c_receipt.redmoney
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public Double getRedmoney() {
		return redmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.redmoney
	 * @param redmoney  the value for c_receipt.redmoney
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setRedmoney(Double redmoney) {
		this.redmoney = redmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_receipt.redid
	 * @return  the value of c_receipt.redid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public Long getRedid() {
		return redid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_receipt.redid
	 * @param redid  the value for c_receipt.redid
	 * @mbggenerated  Tue Mar 27 18:08:47 CST 2018
	 */
	public void setRedid(Long redid) {
		this.redid = redid;
	}
}