package com.lcxsfront.model;

public class staffBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.id
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.sid
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private Long sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.phone
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.realname
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.password
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.kfqq
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private String kfqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.stype
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private Integer stype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.context
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.status
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.invitation
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private String invitation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_staff.ctime
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    private String ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.id
     *
     * @return the value of c_staff.id
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.id
     *
     * @param id the value for c_staff.id
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.sid
     *
     * @return the value of c_staff.sid
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.sid
     *
     * @param sid the value for c_staff.sid
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.phone
     *
     * @return the value of c_staff.phone
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.phone
     *
     * @param phone the value for c_staff.phone
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.realname
     *
     * @return the value of c_staff.realname
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.realname
     *
     * @param realname the value for c_staff.realname
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.password
     *
     * @return the value of c_staff.password
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.password
     *
     * @param password the value for c_staff.password
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.kfqq
     *
     * @return the value of c_staff.kfqq
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public String getKfqq() {
        return kfqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.kfqq
     *
     * @param kfqq the value for c_staff.kfqq
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setKfqq(String kfqq) {
        this.kfqq = kfqq == null ? null : kfqq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.stype
     *
     * @return the value of c_staff.stype
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public Integer getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.stype
     *
     * @param stype the value for c_staff.stype
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setStype(Integer stype) {
        this.stype = stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.context
     *
     * @return the value of c_staff.context
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.context
     *
     * @param context the value for c_staff.context
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.status
     *
     * @return the value of c_staff.status
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.status
     *
     * @param status the value for c_staff.status
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.invitation
     *
     * @return the value of c_staff.invitation
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public String getInvitation() {
        return invitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.invitation
     *
     * @param invitation the value for c_staff.invitation
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setInvitation(String invitation) {
        this.invitation = invitation == null ? null : invitation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_staff.ctime
     *
     * @return the value of c_staff.ctime
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_staff.ctime
     *
     * @param ctime the value for c_staff.ctime
     *
     * @mbggenerated Sun Apr 08 14:04:39 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }
}