package com.lcxsfront.model;

public class userBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.id
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.vid
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private Long vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.phone
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.password
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.owninvitation
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private String owninvitation;
    private int limit;
    private int page;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.invitation
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private String invitation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.alipay
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private String alipay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.realname
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.status
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.kf
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private String kf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.ctime
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.ip
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.level
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.id
     *
     * @return the value of c_user.id
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.id
     *
     * @param id the value for c_user.id
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.vid
     *
     * @return the value of c_user.vid
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public Long getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.vid
     *
     * @param vid the value for c_user.vid
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setVid(Long vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.phone
     *
     * @return the value of c_user.phone
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.phone
     *
     * @param phone the value for c_user.phone
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.password
     *
     * @return the value of c_user.password
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.password
     *
     * @param password the value for c_user.password
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.owninvitation
     *
     * @return the value of c_user.owninvitation
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public String getOwninvitation() {
        return owninvitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.owninvitation
     *
     * @param owninvitation the value for c_user.owninvitation
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setOwninvitation(String owninvitation) {
        this.owninvitation = owninvitation == null ? null : owninvitation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.invitation
     *
     * @return the value of c_user.invitation
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public String getInvitation() {
        return invitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.invitation
     *
     * @param invitation the value for c_user.invitation
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setInvitation(String invitation) {
        this.invitation = invitation == null ? null : invitation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.alipay
     *
     * @return the value of c_user.alipay
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public String getAlipay() {
        return alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.alipay
     *
     * @param alipay the value for c_user.alipay
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setAlipay(String alipay) {
        this.alipay = alipay == null ? null : alipay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.realname
     *
     * @return the value of c_user.realname
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.realname
     *
     * @param realname the value for c_user.realname
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.status
     *
     * @return the value of c_user.status
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.status
     *
     * @param status the value for c_user.status
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.kf
     *
     * @return the value of c_user.kf
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public String getKf() {
        return kf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.kf
     *
     * @param kf the value for c_user.kf
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setKf(String kf) {
        this.kf = kf == null ? null : kf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.ctime
     *
     * @return the value of c_user.ctime
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.ctime
     *
     * @param ctime the value for c_user.ctime
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.ip
     *
     * @return the value of c_user.ip
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.ip
     *
     * @param ip the value for c_user.ip
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.level
     *
     * @return the value of c_user.level
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.level
     *
     * @param level the value for c_user.level
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

	public int getLimit() {
		return limit;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public int getPage() {
		return page;
	}

	public void setPage(int page) {
		this.page = page;
	}
}