package com.lcxsfront.mapper;

import com.lcxsfront.model.bankBean;

public interface bankBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    int insert(bankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    int insertSelective(bankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    bankBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    int updateByPrimaryKeySelective(bankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    int updateByPrimaryKey(bankBean record);
    /**
     * 根据vid查找bank信息
     */
    bankBean queryBankByVid(Long vid);
}