package com.lcxsfront.mapper;

import java.util.List;

import com.lcxsfront.model.banner;
import com.lcxsfront.model.frontBean;
import com.lcxsfront.model.noteBean;
import com.lcxsfront.model.productMessageBean;
import com.lcxsfront.model.shopBean;

public interface shopBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 19 14:18:14 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 19 14:18:14 CST 2018
     */
    int insert(shopBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 19 14:18:14 CST 2018
     */
    int insertSelective(shopBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 19 14:18:14 CST 2018
     */
    shopBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 19 14:18:14 CST 2018
     */
    int updateByPrimaryKeySelective(shopBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 19 14:18:14 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(shopBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 19 14:18:14 CST 2018
     */
    int updateByPrimaryKey(shopBean record);
    /**
     * 查询所有首页信息
     */
    List<frontBean> queryAll(frontBean front);
    /**
     * 查询一共有多少在线商户
     */
    List<Object> queryShopList(frontBean front);
    /**
     * 查询所有横幅
     */
    List<banner> queryBanner();
    /**
     * 查询所有横幅
     */
    List<banner> queryBannerForApp();
    /**
     * 查询轮播logo
     */
    List<shopBean> queryLogo();
    /**
     * 查询关于我们中合作平台简介
     */
    List<shopBean> queryShopSmall(noteBean note);
    /**
     * 分页查询商品
     */
    List<frontBean> queryShopListByFy(frontBean front);
    /**
     * 根据产品id查询信息
     */
    productMessageBean queryProductByPid(Long pid);
    /**
     * 查询一共有多少商家
     */
    Integer queryAllShop();
}