package com.lcxsfront.mapper;

import com.lcxsfront.model.personMessage;
import com.lcxsfront.model.userBean;
import com.lcxsfront.model.userFriendReceiptBean;
import com.lcxsfront.model.userReceiptMessage;

import java.util.List;

public interface userBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    int insert(userBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    int insertSelective(userBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    userBean selectByPrimaryKey(Long vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    int updateByPrimaryKeySelective(userBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Tue Mar 20 16:48:56 CST 2018
     */
    int updateByPrimaryKey(userBean record);
    /**
     * 查询这个用户总收益
     */
    Object queryTotalMoneyByVid(Long vid);
    /**
     * 查询用户投资总额
     */
    Object queryTMoneyByVid(Long vid);
    /**
     * 查询这个用户当日收益
     */
    Object queryTodayMoneyByVid(Long vid);
    /**
     * 查询这个用户未审核回单数
     */
    List<Object> qeuryReceiptByVid(Long vid);
    /**
     * 分页查询这个用户所有回单信息
     */
    List<userReceiptMessage> queryAllMessageByVid(userBean user);
    /**
     * 查询这个用户所有回单信息不分页
     */
    Object queryReceiptNumByVid(userBean user);
    /**
     * 查询用户手机银行卡信息
     */
    personMessage queryPersonMessageByVid(Long vid);
    /**
     * 用户登录
     */
    userBean login(userBean user);
    /**
     * 查询所有用户的手机号码
     */
    List<String> queryPhone();
    /**
     * 分页查询用户邀请人的回单状态
     */
    List<userFriendReceiptBean> queryUserFriendReceipt(userFriendReceiptBean uf);
    /**
     * 查询用户邀请人的回单数量
     */
    Object queryUserFriendReceiptNum(String ucode);
    /**
     * 查询邀请人数根据邀请码
     */
    Object queryInvitationNumByUcode(String ucode);
    /**
     * 查询邀请人中有多少人已经投资了
     */
    List<Long> queryNumByUcde(String ucode);
    /**
     * 查询通过邀请获得了多少金额
     */
    Double queryMoneyByUcode(String ucode);
    /**
     * 查询通过邀请已打款了多少金额
     */
    Object queryDkmoneyByUcode(String ucode);
    /**
     * 根据手机号查询用户信息
     */
    userBean queryUserByPhone(String phone);
    /**
     * 查询用户是否投资
     */
    List<Object> queryNumByVid(Long vid);
        /*
    根据邀请码查询用户
     */

    userBean queryUserByOwninvitation(String invitationCode);

    int updateOwnByVid(long vid);

}