package com.lcxsfront.model;

public class bankBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_bank.id
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_bank.cardid
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_bank.type
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_bank.obank
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    private String obank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_bank.address
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_bank.context
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_bank.ctime
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_bank.name
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_bank.id
     *
     * @return the value of c_bank.id
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_bank.id
     *
     * @param id the value for c_bank.id
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_bank.cardid
     *
     * @return the value of c_bank.cardid
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_bank.cardid
     *
     * @param cardid the value for c_bank.cardid
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_bank.type
     *
     * @return the value of c_bank.type
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_bank.type
     *
     * @param type the value for c_bank.type
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_bank.obank
     *
     * @return the value of c_bank.obank
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public String getObank() {
        return obank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_bank.obank
     *
     * @param obank the value for c_bank.obank
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public void setObank(String obank) {
        this.obank = obank == null ? null : obank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_bank.address
     *
     * @return the value of c_bank.address
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_bank.address
     *
     * @param address the value for c_bank.address
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_bank.context
     *
     * @return the value of c_bank.context
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_bank.context
     *
     * @param context the value for c_bank.context
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_bank.ctime
     *
     * @return the value of c_bank.ctime
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_bank.ctime
     *
     * @param ctime the value for c_bank.ctime
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_bank.name
     *
     * @return the value of c_bank.name
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_bank.name
     *
     * @param name the value for c_bank.name
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}