package com.lcxsfront.model;

public class inviBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_invitation.id
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_invitation.userid
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_invitation.ucode
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    private String ucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_invitation.ljmoney
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    private Double ljmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_invitation.dkmoney
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    private Double dkmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_invitation.ctime
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_invitation.mtime
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    private String mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_invitation.id
     *
     * @return the value of c_invitation.id
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_invitation.id
     *
     * @param id the value for c_invitation.id
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_invitation.userid
     *
     * @return the value of c_invitation.userid
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_invitation.userid
     *
     * @param userid the value for c_invitation.userid
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_invitation.ucode
     *
     * @return the value of c_invitation.ucode
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public String getUcode() {
        return ucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_invitation.ucode
     *
     * @param ucode the value for c_invitation.ucode
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public void setUcode(String ucode) {
        this.ucode = ucode == null ? null : ucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_invitation.ljmoney
     *
     * @return the value of c_invitation.ljmoney
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public Double getLjmoney() {
        return ljmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_invitation.ljmoney
     *
     * @param ljmoney the value for c_invitation.ljmoney
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public void setLjmoney(Double ljmoney) {
        this.ljmoney = ljmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_invitation.dkmoney
     *
     * @return the value of c_invitation.dkmoney
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public Double getDkmoney() {
        return dkmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_invitation.dkmoney
     *
     * @param dkmoney the value for c_invitation.dkmoney
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public void setDkmoney(Double dkmoney) {
        this.dkmoney = dkmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_invitation.ctime
     *
     * @return the value of c_invitation.ctime
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_invitation.ctime
     *
     * @param ctime the value for c_invitation.ctime
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_invitation.mtime
     *
     * @return the value of c_invitation.mtime
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public String getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_invitation.mtime
     *
     * @param mtime the value for c_invitation.mtime
     *
     * @mbggenerated Thu Apr 12 15:47:59 CST 2018
     */
    public void setMtime(String mtime) {
        this.mtime = mtime == null ? null : mtime.trim();
    }
}