package com.lcxsfront.model;

public class productBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.id
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.pid
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.pname
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.minmoney
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Double minmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.maxmoney
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Double maxmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.shopname
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String shopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.shopid
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Long shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.changurl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String changurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.channel
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.level
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.maxfl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Double maxfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.ynh
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String ynh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.schedule
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Integer schedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.xnh
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String xnh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.sort
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.status
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.ctime
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.dtime
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String dtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.qx
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String qx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.typestz
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String typestz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.typesyl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String typesyl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.people
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Long people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.jb
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private Integer jb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.appurl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String appurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.example
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String example;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.zhnh
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String zhnh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_product.context
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.id
     *
     * @return the value of c_product.id
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.id
     *
     * @param id the value for c_product.id
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.pid
     *
     * @return the value of c_product.pid
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.pid
     *
     * @param pid the value for c_product.pid
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.pname
     *
     * @return the value of c_product.pname
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.pname
     *
     * @param pname the value for c_product.pname
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.minmoney
     *
     * @return the value of c_product.minmoney
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Double getMinmoney() {
        return minmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.minmoney
     *
     * @param minmoney the value for c_product.minmoney
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setMinmoney(Double minmoney) {
        this.minmoney = minmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.maxmoney
     *
     * @return the value of c_product.maxmoney
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Double getMaxmoney() {
        return maxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.maxmoney
     *
     * @param maxmoney the value for c_product.maxmoney
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setMaxmoney(Double maxmoney) {
        this.maxmoney = maxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.shopname
     *
     * @return the value of c_product.shopname
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.shopname
     *
     * @param shopname the value for c_product.shopname
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.shopid
     *
     * @return the value of c_product.shopid
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Long getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.shopid
     *
     * @param shopid the value for c_product.shopid
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setShopid(Long shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.changurl
     *
     * @return the value of c_product.changurl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getChangurl() {
        return changurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.changurl
     *
     * @param changurl the value for c_product.changurl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setChangurl(String changurl) {
        this.changurl = changurl == null ? null : changurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.channel
     *
     * @return the value of c_product.channel
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.channel
     *
     * @param channel the value for c_product.channel
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.level
     *
     * @return the value of c_product.level
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.level
     *
     * @param level the value for c_product.level
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.maxfl
     *
     * @return the value of c_product.maxfl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Double getMaxfl() {
        return maxfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.maxfl
     *
     * @param maxfl the value for c_product.maxfl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setMaxfl(Double maxfl) {
        this.maxfl = maxfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.ynh
     *
     * @return the value of c_product.ynh
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getYnh() {
        return ynh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.ynh
     *
     * @param ynh the value for c_product.ynh
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setYnh(String ynh) {
        this.ynh = ynh == null ? null : ynh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.schedule
     *
     * @return the value of c_product.schedule
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Integer getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.schedule
     *
     * @param schedule the value for c_product.schedule
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setSchedule(Integer schedule) {
        this.schedule = schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.xnh
     *
     * @return the value of c_product.xnh
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getXnh() {
        return xnh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.xnh
     *
     * @param xnh the value for c_product.xnh
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setXnh(String xnh) {
        this.xnh = xnh == null ? null : xnh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.sort
     *
     * @return the value of c_product.sort
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.sort
     *
     * @param sort the value for c_product.sort
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.status
     *
     * @return the value of c_product.status
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.status
     *
     * @param status the value for c_product.status
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.ctime
     *
     * @return the value of c_product.ctime
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.ctime
     *
     * @param ctime the value for c_product.ctime
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.dtime
     *
     * @return the value of c_product.dtime
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.dtime
     *
     * @param dtime the value for c_product.dtime
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setDtime(String dtime) {
        this.dtime = dtime == null ? null : dtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.qx
     *
     * @return the value of c_product.qx
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getQx() {
        return qx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.qx
     *
     * @param qx the value for c_product.qx
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setQx(String qx) {
        this.qx = qx == null ? null : qx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.typestz
     *
     * @return the value of c_product.typestz
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getTypestz() {
        return typestz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.typestz
     *
     * @param typestz the value for c_product.typestz
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setTypestz(String typestz) {
        this.typestz = typestz == null ? null : typestz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.typesyl
     *
     * @return the value of c_product.typesyl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getTypesyl() {
        return typesyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.typesyl
     *
     * @param typesyl the value for c_product.typesyl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setTypesyl(String typesyl) {
        this.typesyl = typesyl == null ? null : typesyl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.people
     *
     * @return the value of c_product.people
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Long getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.people
     *
     * @param people the value for c_product.people
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setPeople(Long people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.jb
     *
     * @return the value of c_product.jb
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public Integer getJb() {
        return jb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.jb
     *
     * @param jb the value for c_product.jb
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setJb(Integer jb) {
        this.jb = jb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.appurl
     *
     * @return the value of c_product.appurl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getAppurl() {
        return appurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.appurl
     *
     * @param appurl the value for c_product.appurl
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setAppurl(String appurl) {
        this.appurl = appurl == null ? null : appurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.example
     *
     * @return the value of c_product.example
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getExample() {
        return example;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.example
     *
     * @param example the value for c_product.example
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setExample(String example) {
        this.example = example == null ? null : example.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.zhnh
     *
     * @return the value of c_product.zhnh
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getZhnh() {
        return zhnh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.zhnh
     *
     * @param zhnh the value for c_product.zhnh
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setZhnh(String zhnh) {
        this.zhnh = zhnh == null ? null : zhnh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_product.context
     *
     * @return the value of c_product.context
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_product.context
     *
     * @param context the value for c_product.context
     *
     * @mbggenerated Wed Mar 28 09:48:22 CST 2018
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}