package com.lcxsfront.model;

public class redBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.id
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.redid
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private Long redid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.redname
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private String redname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.redmoney
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private Double redmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.redCondition
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private Long redcondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.lqtj
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private String lqtj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.days
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.context
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.status
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.ctime
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_red.dtime
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    private String dtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.id
     *
     * @return the value of c_red.id
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.id
     *
     * @param id the value for c_red.id
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.redid
     *
     * @return the value of c_red.redid
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public Long getRedid() {
        return redid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.redid
     *
     * @param redid the value for c_red.redid
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setRedid(Long redid) {
        this.redid = redid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.redname
     *
     * @return the value of c_red.redname
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public String getRedname() {
        return redname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.redname
     *
     * @param redname the value for c_red.redname
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setRedname(String redname) {
        this.redname = redname == null ? null : redname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.redmoney
     *
     * @return the value of c_red.redmoney
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public Double getRedmoney() {
        return redmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.redmoney
     *
     * @param redmoney the value for c_red.redmoney
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setRedmoney(Double redmoney) {
        this.redmoney = redmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.redCondition
     *
     * @return the value of c_red.redCondition
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public Long getRedcondition() {
        return redcondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.redCondition
     *
     * @param redcondition the value for c_red.redCondition
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setRedcondition(Long redcondition) {
        this.redcondition = redcondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.lqtj
     *
     * @return the value of c_red.lqtj
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public String getLqtj() {
        return lqtj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.lqtj
     *
     * @param lqtj the value for c_red.lqtj
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setLqtj(String lqtj) {
        this.lqtj = lqtj == null ? null : lqtj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.days
     *
     * @return the value of c_red.days
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.days
     *
     * @param days the value for c_red.days
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.context
     *
     * @return the value of c_red.context
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.context
     *
     * @param context the value for c_red.context
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.status
     *
     * @return the value of c_red.status
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.status
     *
     * @param status the value for c_red.status
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.ctime
     *
     * @return the value of c_red.ctime
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.ctime
     *
     * @param ctime the value for c_red.ctime
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_red.dtime
     *
     * @return the value of c_red.dtime
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public String getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_red.dtime
     *
     * @param dtime the value for c_red.dtime
     *
     * @mbggenerated Mon Apr 02 10:48:33 CST 2018
     */
    public void setDtime(String dtime) {
        this.dtime = dtime == null ? null : dtime.trim();
    }
}