package com.lcxsfront.model;

public class userReceiptBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_receipt.id
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_receipt.vid
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    private Long vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_receipt.rid
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    private Long rid;

    public userReceiptBean() {
		super();
	}

	public userReceiptBean(Long vid, Long rid) {
		super();
		this.vid = vid;
		this.rid = rid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_receipt.id
     *
     * @return the value of c_user_receipt.id
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_receipt.id
     *
     * @param id the value for c_user_receipt.id
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_receipt.vid
     *
     * @return the value of c_user_receipt.vid
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    public Long getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_receipt.vid
     *
     * @param vid the value for c_user_receipt.vid
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    public void setVid(Long vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_receipt.rid
     *
     * @return the value of c_user_receipt.rid
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_receipt.rid
     *
     * @param rid the value for c_user_receipt.rid
     *
     * @mbggenerated Wed Mar 28 09:46:17 CST 2018
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }
}