package com.lcxsfront.model;

public class userRedBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_red.id
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    private Long id;

    private String de;
    public userRedBean() {
		super();
	}

	public userRedBean(Long vid, Long redid, Double redmoney,
			Long redcondition, String ctime, String redname, Integer days,
			String type, String context) {
		super();
		this.vid = vid;
		this.redid = redid;
		this.redmoney = redmoney;
		this.redcondition = redcondition;
		this.ctime = ctime;
		this.redname = redname;
		this.days = days;
		this.type = type;
		this.context = context;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_red.vid
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    private Long vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_red.redid
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    private Long redid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_red.redmoney
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    private Double redmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_red.redCondition
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    private Long redcondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_red.ctime
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_red.redname
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    private String redname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_red.days
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_red.type
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_red.context
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_red.id
     *
     * @return the value of c_user_red.id
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_red.id
     *
     * @param id the value for c_user_red.id
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_red.vid
     *
     * @return the value of c_user_red.vid
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public Long getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_red.vid
     *
     * @param vid the value for c_user_red.vid
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public void setVid(Long vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_red.redid
     *
     * @return the value of c_user_red.redid
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public Long getRedid() {
        return redid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_red.redid
     *
     * @param redid the value for c_user_red.redid
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public void setRedid(Long redid) {
        this.redid = redid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_red.redmoney
     *
     * @return the value of c_user_red.redmoney
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public Double getRedmoney() {
        return redmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_red.redmoney
     *
     * @param redmoney the value for c_user_red.redmoney
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public void setRedmoney(Double redmoney) {
        this.redmoney = redmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_red.redCondition
     *
     * @return the value of c_user_red.redCondition
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public Long getRedcondition() {
        return redcondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_red.redCondition
     *
     * @param redcondition the value for c_user_red.redCondition
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public void setRedcondition(Long redcondition) {
        this.redcondition = redcondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_red.ctime
     *
     * @return the value of c_user_red.ctime
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_red.ctime
     *
     * @param ctime the value for c_user_red.ctime
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_red.redname
     *
     * @return the value of c_user_red.redname
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public String getRedname() {
        return redname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_red.redname
     *
     * @param redname the value for c_user_red.redname
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public void setRedname(String redname) {
        this.redname = redname == null ? null : redname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_red.days
     *
     * @return the value of c_user_red.days
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_red.days
     *
     * @param days the value for c_user_red.days
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_red.type
     *
     * @return the value of c_user_red.type
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_red.type
     *
     * @param type the value for c_user_red.type
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_red.context
     *
     * @return the value of c_user_red.context
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_red.context
     *
     * @param context the value for c_user_red.context
     *
     * @mbggenerated Thu Apr 12 17:00:44 CST 2018
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

	public String getDe() {
		return de;
	}

	public void setDe(String de) {
		this.de = de;
	}
}